/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiciliaRouteImport } from './routes/sicilia'
import { Route as NapoliRouteImport } from './routes/napoli'
import { Route as ChiesaDiCristoDiBolognaRecruitmentPageRouteImport } from './routes/chiesa-di-cristo-di-bologna-recruitment-page'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RisorseIndexRouteImport } from './routes/risorse.index'
import { Route as MilanoIndexRouteImport } from './routes/milano.index'
import { Route as DevozionaleIndexRouteImport } from './routes/devozionale.index'
import { Route as BolognaIndexRouteImport } from './routes/bologna.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RisorseSlugRouteImport } from './routes/risorse.$slug'
import { Route as MilanoVisitaRouteImport } from './routes/milano.visita'
import { Route as MilanoEventiRouteImport } from './routes/milano.eventi'
import { Route as MilanoCosaCrediamoRouteImport } from './routes/milano.cosa-crediamo'
import { Route as MilanoContattiRouteImport } from './routes/milano.contatti'
import { Route as MilanoChiSiamoRouteImport } from './routes/milano.chi-siamo'
import { Route as BolognaVisitaRouteImport } from './routes/bologna.visita'
import { Route as BolognaEventiRouteImport } from './routes/bologna.eventi'
import { Route as BolognaCosaCrediamoRouteImport } from './routes/bologna.cosa-crediamo'
import { Route as BolognaContattiRouteImport } from './routes/bologna.contatti'
import { Route as BolognaChiSiamoRouteImport } from './routes/bologna.chi-siamo'
import { Route as AdminMessaggiRouteImport } from './routes/admin.messaggi'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminEventiRouteImport } from './routes/admin.eventi'
import { Route as AdminDevozionaliIndexRouteImport } from './routes/admin.devozionali.index'
import { Route as AdminRisorseIdRouteImport } from './routes/admin.risorse.$id'
import { Route as AdminDevozionaliIdRouteImport } from './routes/admin.devozionali.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const SiciliaRoute = SiciliaRouteImport.update({
  id: '/sicilia',
  path: '/sicilia',
  getParentRoute: () => rootRouteImport,
} as any)
const NapoliRoute = NapoliRouteImport.update({
  id: '/napoli',
  path: '/napoli',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiesaDiCristoDiBolognaRecruitmentPageRoute =
  ChiesaDiCristoDiBolognaRecruitmentPageRouteImport.update({
    id: '/chiesa-di-cristo-di-bologna-recruitment-page',
    path: '/chiesa-di-cristo-di-bologna-recruitment-page',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RisorseIndexRoute = RisorseIndexRouteImport.update({
  id: '/risorse/',
  path: '/risorse/',
  getParentRoute: () => rootRouteImport,
} as any)
const MilanoIndexRoute = MilanoIndexRouteImport.update({
  id: '/milano/',
  path: '/milano/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevozionaleIndexRoute = DevozionaleIndexRouteImport.update({
  id: '/devozionale/',
  path: '/devozionale/',
  getParentRoute: () => rootRouteImport,
} as any)
const BolognaIndexRoute = BolognaIndexRouteImport.update({
  id: '/bologna/',
  path: '/bologna/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RisorseSlugRoute = RisorseSlugRouteImport.update({
  id: '/risorse/$slug',
  path: '/risorse/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MilanoVisitaRoute = MilanoVisitaRouteImport.update({
  id: '/milano/visita',
  path: '/milano/visita',
  getParentRoute: () => rootRouteImport,
} as any)
const MilanoEventiRoute = MilanoEventiRouteImport.update({
  id: '/milano/eventi',
  path: '/milano/eventi',
  getParentRoute: () => rootRouteImport,
} as any)
const MilanoCosaCrediamoRoute = MilanoCosaCrediamoRouteImport.update({
  id: '/milano/cosa-crediamo',
  path: '/milano/cosa-crediamo',
  getParentRoute: () => rootRouteImport,
} as any)
const MilanoContattiRoute = MilanoContattiRouteImport.update({
  id: '/milano/contatti',
  path: '/milano/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const MilanoChiSiamoRoute = MilanoChiSiamoRouteImport.update({
  id: '/milano/chi-siamo',
  path: '/milano/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const BolognaVisitaRoute = BolognaVisitaRouteImport.update({
  id: '/bologna/visita',
  path: '/bologna/visita',
  getParentRoute: () => rootRouteImport,
} as any)
const BolognaEventiRoute = BolognaEventiRouteImport.update({
  id: '/bologna/eventi',
  path: '/bologna/eventi',
  getParentRoute: () => rootRouteImport,
} as any)
const BolognaCosaCrediamoRoute = BolognaCosaCrediamoRouteImport.update({
  id: '/bologna/cosa-crediamo',
  path: '/bologna/cosa-crediamo',
  getParentRoute: () => rootRouteImport,
} as any)
const BolognaContattiRoute = BolognaContattiRouteImport.update({
  id: '/bologna/contatti',
  path: '/bologna/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const BolognaChiSiamoRoute = BolognaChiSiamoRouteImport.update({
  id: '/bologna/chi-siamo',
  path: '/bologna/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessaggiRoute = AdminMessaggiRouteImport.update({
  id: '/messaggi',
  path: '/messaggi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventiRoute = AdminEventiRouteImport.update({
  id: '/eventi',
  path: '/eventi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevozionaliIndexRoute = AdminDevozionaliIndexRouteImport.update({
  id: '/devozionali/',
  path: '/devozionali/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRisorseIdRoute = AdminRisorseIdRouteImport.update({
  id: '/risorse/$id',
  path: '/risorse/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevozionaliIdRoute = AdminDevozionaliIdRouteImport.update({
  id: '/devozionali/$id',
  path: '/devozionali/$id',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/chiesa-di-cristo-di-bologna-recruitment-page': typeof ChiesaDiCristoDiBolognaRecruitmentPageRoute
  '/napoli': typeof NapoliRoute
  '/sicilia': typeof SiciliaRoute
  '/admin/eventi': typeof AdminEventiRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messaggi': typeof AdminMessaggiRoute
  '/bologna/chi-siamo': typeof BolognaChiSiamoRoute
  '/bologna/contatti': typeof BolognaContattiRoute
  '/bologna/cosa-crediamo': typeof BolognaCosaCrediamoRoute
  '/bologna/eventi': typeof BolognaEventiRoute
  '/bologna/visita': typeof BolognaVisitaRoute
  '/milano/chi-siamo': typeof MilanoChiSiamoRoute
  '/milano/contatti': typeof MilanoContattiRoute
  '/milano/cosa-crediamo': typeof MilanoCosaCrediamoRoute
  '/milano/eventi': typeof MilanoEventiRoute
  '/milano/visita': typeof MilanoVisitaRoute
  '/risorse/$slug': typeof RisorseSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/bologna/': typeof BolognaIndexRoute
  '/devozionale/': typeof DevozionaleIndexRoute
  '/milano/': typeof MilanoIndexRoute
  '/risorse/': typeof RisorseIndexRoute
  '/admin/devozionali/$id': typeof AdminDevozionaliIdRoute
  '/admin/risorse/$id': typeof AdminRisorseIdRoute
  '/admin/devozionali/': typeof AdminDevozionaliIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chiesa-di-cristo-di-bologna-recruitment-page': typeof ChiesaDiCristoDiBolognaRecruitmentPageRoute
  '/napoli': typeof NapoliRoute
  '/sicilia': typeof SiciliaRoute
  '/admin/eventi': typeof AdminEventiRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messaggi': typeof AdminMessaggiRoute
  '/bologna/chi-siamo': typeof BolognaChiSiamoRoute
  '/bologna/contatti': typeof BolognaContattiRoute
  '/bologna/cosa-crediamo': typeof BolognaCosaCrediamoRoute
  '/bologna/eventi': typeof BolognaEventiRoute
  '/bologna/visita': typeof BolognaVisitaRoute
  '/milano/chi-siamo': typeof MilanoChiSiamoRoute
  '/milano/contatti': typeof MilanoContattiRoute
  '/milano/cosa-crediamo': typeof MilanoCosaCrediamoRoute
  '/milano/eventi': typeof MilanoEventiRoute
  '/milano/visita': typeof MilanoVisitaRoute
  '/risorse/$slug': typeof RisorseSlugRoute
  '/admin': typeof AdminIndexRoute
  '/bologna': typeof BolognaIndexRoute
  '/devozionale': typeof DevozionaleIndexRoute
  '/milano': typeof MilanoIndexRoute
  '/risorse': typeof RisorseIndexRoute
  '/admin/devozionali/$id': typeof AdminDevozionaliIdRoute
  '/admin/risorse/$id': typeof AdminRisorseIdRoute
  '/admin/devozionali': typeof AdminDevozionaliIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/chiesa-di-cristo-di-bologna-recruitment-page': typeof ChiesaDiCristoDiBolognaRecruitmentPageRoute
  '/napoli': typeof NapoliRoute
  '/sicilia': typeof SiciliaRoute
  '/admin/eventi': typeof AdminEventiRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messaggi': typeof AdminMessaggiRoute
  '/bologna/chi-siamo': typeof BolognaChiSiamoRoute
  '/bologna/contatti': typeof BolognaContattiRoute
  '/bologna/cosa-crediamo': typeof BolognaCosaCrediamoRoute
  '/bologna/eventi': typeof BolognaEventiRoute
  '/bologna/visita': typeof BolognaVisitaRoute
  '/milano/chi-siamo': typeof MilanoChiSiamoRoute
  '/milano/contatti': typeof MilanoContattiRoute
  '/milano/cosa-crediamo': typeof MilanoCosaCrediamoRoute
  '/milano/eventi': typeof MilanoEventiRoute
  '/milano/visita': typeof MilanoVisitaRoute
  '/risorse/$slug': typeof RisorseSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/bologna/': typeof BolognaIndexRoute
  '/devozionale/': typeof DevozionaleIndexRoute
  '/milano/': typeof MilanoIndexRoute
  '/risorse/': typeof RisorseIndexRoute
  '/admin/devozionali/$id': typeof AdminDevozionaliIdRoute
  '/admin/risorse/$id': typeof AdminRisorseIdRoute
  '/admin/devozionali/': typeof AdminDevozionaliIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chiesa-di-cristo-di-bologna-recruitment-page'
    | '/napoli'
    | '/sicilia'
    | '/admin/eventi'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/media'
    | '/admin/messaggi'
    | '/bologna/chi-siamo'
    | '/bologna/contatti'
    | '/bologna/cosa-crediamo'
    | '/bologna/eventi'
    | '/bologna/visita'
    | '/milano/chi-siamo'
    | '/milano/contatti'
    | '/milano/cosa-crediamo'
    | '/milano/eventi'
    | '/milano/visita'
    | '/risorse/$slug'
    | '/admin/'
    | '/bologna/'
    | '/devozionale/'
    | '/milano/'
    | '/risorse/'
    | '/admin/devozionali/$id'
    | '/admin/risorse/$id'
    | '/admin/devozionali/'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chiesa-di-cristo-di-bologna-recruitment-page'
    | '/napoli'
    | '/sicilia'
    | '/admin/eventi'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/media'
    | '/admin/messaggi'
    | '/bologna/chi-siamo'
    | '/bologna/contatti'
    | '/bologna/cosa-crediamo'
    | '/bologna/eventi'
    | '/bologna/visita'
    | '/milano/chi-siamo'
    | '/milano/contatti'
    | '/milano/cosa-crediamo'
    | '/milano/eventi'
    | '/milano/visita'
    | '/risorse/$slug'
    | '/admin'
    | '/bologna'
    | '/devozionale'
    | '/milano'
    | '/risorse'
    | '/admin/devozionali/$id'
    | '/admin/risorse/$id'
    | '/admin/devozionali'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chiesa-di-cristo-di-bologna-recruitment-page'
    | '/napoli'
    | '/sicilia'
    | '/admin/eventi'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/media'
    | '/admin/messaggi'
    | '/bologna/chi-siamo'
    | '/bologna/contatti'
    | '/bologna/cosa-crediamo'
    | '/bologna/eventi'
    | '/bologna/visita'
    | '/milano/chi-siamo'
    | '/milano/contatti'
    | '/milano/cosa-crediamo'
    | '/milano/eventi'
    | '/milano/visita'
    | '/risorse/$slug'
    | '/admin/'
    | '/bologna/'
    | '/devozionale/'
    | '/milano/'
    | '/risorse/'
    | '/admin/devozionali/$id'
    | '/admin/risorse/$id'
    | '/admin/devozionali/'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChiesaDiCristoDiBolognaRecruitmentPageRoute: typeof ChiesaDiCristoDiBolognaRecruitmentPageRoute
  NapoliRoute: typeof NapoliRoute
  SiciliaRoute: typeof SiciliaRoute
  BolognaChiSiamoRoute: typeof BolognaChiSiamoRoute
  BolognaContattiRoute: typeof BolognaContattiRoute
  BolognaCosaCrediamoRoute: typeof BolognaCosaCrediamoRoute
  BolognaEventiRoute: typeof BolognaEventiRoute
  BolognaVisitaRoute: typeof BolognaVisitaRoute
  MilanoChiSiamoRoute: typeof MilanoChiSiamoRoute
  MilanoContattiRoute: typeof MilanoContattiRoute
  MilanoCosaCrediamoRoute: typeof MilanoCosaCrediamoRoute
  MilanoEventiRoute: typeof MilanoEventiRoute
  MilanoVisitaRoute: typeof MilanoVisitaRoute
  RisorseSlugRoute: typeof RisorseSlugRoute
  BolognaIndexRoute: typeof BolognaIndexRoute
  DevozionaleIndexRoute: typeof DevozionaleIndexRoute
  MilanoIndexRoute: typeof MilanoIndexRoute
  RisorseIndexRoute: typeof RisorseIndexRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sicilia': {
      id: '/sicilia'
      path: '/sicilia'
      fullPath: '/sicilia'
      preLoaderRoute: typeof SiciliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/napoli': {
      id: '/napoli'
      path: '/napoli'
      fullPath: '/napoli'
      preLoaderRoute: typeof NapoliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chiesa-di-cristo-di-bologna-recruitment-page': {
      id: '/chiesa-di-cristo-di-bologna-recruitment-page'
      path: '/chiesa-di-cristo-di-bologna-recruitment-page'
      fullPath: '/chiesa-di-cristo-di-bologna-recruitment-page'
      preLoaderRoute: typeof ChiesaDiCristoDiBolognaRecruitmentPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risorse/': {
      id: '/risorse/'
      path: '/risorse'
      fullPath: '/risorse/'
      preLoaderRoute: typeof RisorseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milano/': {
      id: '/milano/'
      path: '/milano'
      fullPath: '/milano/'
      preLoaderRoute: typeof MilanoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devozionale/': {
      id: '/devozionale/'
      path: '/devozionale'
      fullPath: '/devozionale/'
      preLoaderRoute: typeof DevozionaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bologna/': {
      id: '/bologna/'
      path: '/bologna'
      fullPath: '/bologna/'
      preLoaderRoute: typeof BolognaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/risorse/$slug': {
      id: '/risorse/$slug'
      path: '/risorse/$slug'
      fullPath: '/risorse/$slug'
      preLoaderRoute: typeof RisorseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milano/visita': {
      id: '/milano/visita'
      path: '/milano/visita'
      fullPath: '/milano/visita'
      preLoaderRoute: typeof MilanoVisitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milano/eventi': {
      id: '/milano/eventi'
      path: '/milano/eventi'
      fullPath: '/milano/eventi'
      preLoaderRoute: typeof MilanoEventiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milano/cosa-crediamo': {
      id: '/milano/cosa-crediamo'
      path: '/milano/cosa-crediamo'
      fullPath: '/milano/cosa-crediamo'
      preLoaderRoute: typeof MilanoCosaCrediamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milano/contatti': {
      id: '/milano/contatti'
      path: '/milano/contatti'
      fullPath: '/milano/contatti'
      preLoaderRoute: typeof MilanoContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milano/chi-siamo': {
      id: '/milano/chi-siamo'
      path: '/milano/chi-siamo'
      fullPath: '/milano/chi-siamo'
      preLoaderRoute: typeof MilanoChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bologna/visita': {
      id: '/bologna/visita'
      path: '/bologna/visita'
      fullPath: '/bologna/visita'
      preLoaderRoute: typeof BolognaVisitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bologna/eventi': {
      id: '/bologna/eventi'
      path: '/bologna/eventi'
      fullPath: '/bologna/eventi'
      preLoaderRoute: typeof BolognaEventiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bologna/cosa-crediamo': {
      id: '/bologna/cosa-crediamo'
      path: '/bologna/cosa-crediamo'
      fullPath: '/bologna/cosa-crediamo'
      preLoaderRoute: typeof BolognaCosaCrediamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bologna/contatti': {
      id: '/bologna/contatti'
      path: '/bologna/contatti'
      fullPath: '/bologna/contatti'
      preLoaderRoute: typeof BolognaContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bologna/chi-siamo': {
      id: '/bologna/chi-siamo'
      path: '/bologna/chi-siamo'
      fullPath: '/bologna/chi-siamo'
      preLoaderRoute: typeof BolognaChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messaggi': {
      id: '/admin/messaggi'
      path: '/messaggi'
      fullPath: '/admin/messaggi'
      preLoaderRoute: typeof AdminMessaggiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eventi': {
      id: '/admin/eventi'
      path: '/eventi'
      fullPath: '/admin/eventi'
      preLoaderRoute: typeof AdminEventiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devozionali/': {
      id: '/admin/devozionali/'
      path: '/devozionali'
      fullPath: '/admin/devozionali/'
      preLoaderRoute: typeof AdminDevozionaliIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/risorse/$id': {
      id: '/admin/risorse/$id'
      path: '/risorse/$id'
      fullPath: '/admin/risorse/$id'
      preLoaderRoute: typeof AdminRisorseIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devozionali/$id': {
      id: '/admin/devozionali/$id'
      path: '/devozionali/$id'
      fullPath: '/admin/devozionali/$id'
      preLoaderRoute: typeof AdminDevozionaliIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminEventiRoute: typeof AdminEventiRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMessaggiRoute: typeof AdminMessaggiRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDevozionaliIdRoute: typeof AdminDevozionaliIdRoute
  AdminRisorseIdRoute: typeof AdminRisorseIdRoute
  AdminDevozionaliIndexRoute: typeof AdminDevozionaliIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEventiRoute: AdminEventiRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMessaggiRoute: AdminMessaggiRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDevozionaliIdRoute: AdminDevozionaliIdRoute,
  AdminRisorseIdRoute: AdminRisorseIdRoute,
  AdminDevozionaliIndexRoute: AdminDevozionaliIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChiesaDiCristoDiBolognaRecruitmentPageRoute:
    ChiesaDiCristoDiBolognaRecruitmentPageRoute,
  NapoliRoute: NapoliRoute,
  SiciliaRoute: SiciliaRoute,
  BolognaChiSiamoRoute: BolognaChiSiamoRoute,
  BolognaContattiRoute: BolognaContattiRoute,
  BolognaCosaCrediamoRoute: BolognaCosaCrediamoRoute,
  BolognaEventiRoute: BolognaEventiRoute,
  BolognaVisitaRoute: BolognaVisitaRoute,
  MilanoChiSiamoRoute: MilanoChiSiamoRoute,
  MilanoContattiRoute: MilanoContattiRoute,
  MilanoCosaCrediamoRoute: MilanoCosaCrediamoRoute,
  MilanoEventiRoute: MilanoEventiRoute,
  MilanoVisitaRoute: MilanoVisitaRoute,
  RisorseSlugRoute: RisorseSlugRoute,
  BolognaIndexRoute: BolognaIndexRoute,
  DevozionaleIndexRoute: DevozionaleIndexRoute,
  MilanoIndexRoute: MilanoIndexRoute,
  RisorseIndexRoute: RisorseIndexRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
