/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MilanoIndexRouteImport } from './routes/milano.index'
import { Route as BolognaIndexRouteImport } from './routes/bologna.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MilanoIndexRoute = MilanoIndexRouteImport.update({
  id: '/milano/',
  path: '/milano/',
  getParentRoute: () => rootRouteImport,
} as any)
const BolognaIndexRoute = BolognaIndexRouteImport.update({
  id: '/bologna/',
  path: '/bologna/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bologna/': typeof BolognaIndexRoute
  '/milano/': typeof MilanoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bologna': typeof BolognaIndexRoute
  '/milano': typeof MilanoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bologna/': typeof BolognaIndexRoute
  '/milano/': typeof MilanoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bologna/' | '/milano/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bologna' | '/milano'
  id: '__root__' | '/' | '/bologna/' | '/milano/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BolognaIndexRoute: typeof BolognaIndexRoute
  MilanoIndexRoute: typeof MilanoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milano/': {
      id: '/milano/'
      path: '/milano'
      fullPath: '/milano/'
      preLoaderRoute: typeof MilanoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bologna/': {
      id: '/bologna/'
      path: '/bologna'
      fullPath: '/bologna/'
      preLoaderRoute: typeof BolognaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BolognaIndexRoute: BolognaIndexRoute,
  MilanoIndexRoute: MilanoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
